---
- name: installing and configuring
  hosts: all
  become: true


  tasks:
  - name: update repo index
    ansible.builtin.apt:
      name:
      update_cache: yes


  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest


  - name: Addition of PHP support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest


